# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: mlproject.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_06F9109C73644E279B61F715FC76C8B1 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4EC9CC485C124E2B9FC900163FCB2368 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mlproject.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_06F9109C73644E279B61F715FC76C8B1 }}/mlproject:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9ABB30E0421B473386F7886265623764 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94753B13986A421FA1C8C9F1AAF4F93D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_48903F997C9542E88EC38A40BC70248C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mlproject'
          slot-name: 'Production'
          images: 'mlproject.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_06F9109C73644E279B61F715FC76C8B1 }}/mlproject:${{ github.sha }}'
          